### ISSUE TITLE
Bug due to Splitting Scrolls.

### ISSUE THREAD

**Issue by nymann** [nymann/Stashie#11]
Log Entry : 13:19:32 16 June 2017
 ```
Method error: Render : System.NullReferenceException: Object reference not set to an instance of an object.
   at Stashie.Core.<>c.<Stashie>b__12_1(Element element) in C:\Users\Nymann\Documents\Stashie\Core.cs:line 229
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stashie.Core.Stashie() in C:\Users\Nymann\Documents\Stashie\Core.cs:line 229
   at Stashie.Core.Render() in C:\Users\Nymann\Documents\Stashie\Core.cs:line 193
   at PoeHUD.Plugins.BasePlugin.iRender()
```
-------------------------------

**Comment by nymann** [comment]
For now, just set scrolls to keep to 40 for both types.

**Comment by nymann** [comment]
Temporary solution implemented. (User has to press hotkey twice).
