### ISSUE TITLE
Spamming error with PoeHUD.Poe.Elements.StashElement.get_IndexVisibleStash()'.

### ISSUE THREAD

**Issue by TSM-EVO** [nymann/Stashie#21]
`
Log Entry : 8:02:25 PM Wednesday, 17 January 2018
 Method error: Render : System.MissingMethodException: Method not found: 'Int32 PoeHUD.Poe.Elements.StashElement.get_IndexVisibleStash()'.
   at Stashie.StashieCore.SwitchToTab(Int32 indexOfTabToVisit)
   at Stashie.StashieCore.DropToStash() in C:\Users\Nymann\Documents\Stashie\StashieCore.cs:line 483
   at Stashie.StashieCore.Render() in C:\Users\Nymann\Documents\Stashie\StashieCore.cs:line 106
   at PoeHUD.Plugins.BasePlugin.iRender()
`

**Comment by TSM-EVO** [comment]
I should note I have updated to the latest poehud, I am fairly sure. 
This happens when I hit the hotkey to move to stash. It locks up my mouse, and I have to ctrl alt del to get control back.

**Comment by zaafar** [comment]
Your update failed. Kindly update poehud manually.
